# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenaqCli < Formula
  desc "Official Command Line Interface for OpenAQ."
  homepage "https://openaq.org"
  version "0.4.2-rc"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openaq/openaq-cli/releases/download/v0.4.2-rc/openaq-cli_0.4.2-rc_darwin_amd64.tar.gz"
      sha256 "3f2ffb299d6c8f984dbefd58f5323af2695552493da88e47b496cda00c4d498f"

      def install
        bin.install "openaq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openaq/openaq-cli/releases/download/v0.4.2-rc/openaq-cli_0.4.2-rc_darwin_arm64.tar.gz"
      sha256 "67bd89731ccacaf8294441b35c7bd61ab6c2767a05562da99143f7ce7c79347c"

      def install
        bin.install "openaq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openaq/openaq-cli/releases/download/v0.4.2-rc/openaq-cli_0.4.2-rc_linux_arm64.tar.gz"
      sha256 "f1f7cded26c616a59c4dafa3cffc71834a1c31ee8a168589cf68509efb222e89"

      def install
        bin.install "openaq"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/openaq/openaq-cli/releases/download/v0.4.2-rc/openaq-cli_0.4.2-rc_linux_amd64.tar.gz"
      sha256 "47efd835741c4c1573b64023a628f2c1d7dd0058b7ed2681a1f32708bc4f6db9"

      def install
        bin.install "openaq"
      end
    end
  end

  test do
    system "#{bin}/openaq-cli -v"
  end
end
