# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenaqCli < Formula
  desc "Official Command Line Interface for OpenAQ."
  homepage "https://openaq.org"
  version "0.4.0-rc"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openaq/openaq-cli/releases/download/v0.4.0-rc/openaq-cli_0.4.0-rc_darwin_amd64.tar.gz"
      sha256 "f8fb56c7dbd7e1fe5bd72913996168cd51dcf68a0786cf39972cce2153a1b67d"

      def install
        bin.install "openaq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openaq/openaq-cli/releases/download/v0.4.0-rc/openaq-cli_0.4.0-rc_darwin_arm64.tar.gz"
      sha256 "a9023844cf2f85aa551a13b8454bf2a8880c46894ba372b8ee2b52b713a01fd8"

      def install
        bin.install "openaq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/openaq/openaq-cli/releases/download/v0.4.0-rc/openaq-cli_0.4.0-rc_linux_amd64.tar.gz"
      sha256 "deec29090409c5a50bc5ab1a161c1e5e521d316ee6188fc9de81a1fd8405480d"

      def install
        bin.install "openaq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openaq/openaq-cli/releases/download/v0.4.0-rc/openaq-cli_0.4.0-rc_linux_arm64.tar.gz"
      sha256 "451ff44cc9054d6ca3dbadf364c3d7fa5a4cba01d120cd1fb7b055e05ffa71b4"

      def install
        bin.install "openaq"
      end
    end
  end

  test do
    system "#{bin}/openaq-cli -v"
  end
end
